### ISSUE TITLE
Error when creating plug-in project

### ISSUE THREAD

**Issue by mtnmuncher** [jlattimer/CRMDeveloperExtensions#1]
I am getting the following error when attempting to create a Plug-in project. I am using VS 2012. Could it be that I already have the CRM Developer Toolkit for CRM 2013 installed?

>>>> START POP UP ERROR
The 'UserOptionsPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\User\AppData\Roaming\Microsoft\VisualStudio\11.0\ActivityLog.xml'.

<<<<<<<< END POP UP ERROR

Error from ActivityLog.xml file.

<entry>
<record>540</record>
<time>2015/06/24 13:58:15.218</time>
<type>Error</type>
<source>VisualStudio</source>
<description>CreateInstance failed for package [UserOptionsPackage]</description>
<guid>{8F9D97A5-8FC7-461C-9A4F-0C4D2E03210F}</guid>
<hr>80070002</hr>
<errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
</entry>
<entry>
<record>541</record>
<time>2015/06/24 13:58:15.218</time>
<type>Error</type>
<source>VisualStudio</source>
<description>End package load [UserOptionsPackage]</description>
<guid>{8F9D97A5-8FC7-461C-9A4F-0C4D2E03210F}</guid>
<hr>80004005 - E_FAIL</hr>
<errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
</entry>

**Comment by jlattimer** [comment]
Can you uninstall and try this version and let me know if it fixes the issue?  [https://dl.dropboxusercontent.com/u/3275131/CRMDeveloperExtensions.vsix](https://dl.dropboxusercontent.com/u/3275131/CRMDeveloperExtensions.vsix)

**Comment by mtnmuncher** [comment]
Below is the error after uninstall, then install of the version mentioned in above link.

  <entry>
    <record>536</record>
    <time>2015/06/24 14:47:37.005</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [UserOptionsPackage]</description>
    <guid>{8F9D97A5-8FC7-461C-9A4F-0C4D2E03210F}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>537</record>
    <time>2015/06/24 14:47:37.005</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [UserOptionsPackage]</description>
    <guid>{8F9D97A5-8FC7-461C-9A4F-0C4D2E03210F}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by jlattimer** [comment]
OK pretty sure I got it figured out. It appears the error doesn't surface when you have a later version of Visual Studio also installed on the same machine. So I built a VM with only VS 2012 and was able to replicate and I believe fix the error. 

Can you uninstall and download the the updated version from the same DropBox link and confirm?

**Comment by mtnmuncher** [comment]
Yes! The latest version of your extension resolved the issue.

**Comment by jlattimer** [comment]
Good deal - I'll be updating the Visual Studio Gallery version shortly - it might be a good idea to uninstall and then grab the v1.0.1.0 from there in a little bit to make sure VS detect future updates.
