### ISSUE TITLE
Just installed CRMDeveloperExtensions for VS2012 - Plugin project incompatible / CRMPackage (needs migration)

### ISSUE THREAD

**Issue by vistasgp888** [jlattimer/CRMDeveloperExtensions#101]
Hello,

I just found CRMDeveloperExtentions today and installed it.

I've noticed the following:

1)My plugin project is now incompatible with the my version of Visual Studio (2012).

2)My old Crm Developer Toolkit  CRMPackage project now says that it (needs migration) next to it.

I've searched the wiki and can't find anything related to this.  

Any ideas on how to move forward?

**Comment by jlattimer** [comment]
This project isn't the same as the CRM Developer Toolkit produces
