### ISSUE TITLE
Extension is not supporting in Visual Studio Community 2017

### ISSUE THREAD

**Issue by venkat2reddy** [jlattimer/CRMDeveloperExtensions#102]
This extension is not installable on Visual Studio Community 2017.

Here is the log file.

5/24/2017 3:33:59 PM - Microsoft VSIX Installer
5/24/2017 3:33:59 PM - -------------------------------------------
5/24/2017 3:33:59 PM - vsixinstaller.exe version:
5/24/2017 3:33:59 PM - 15.0.26323.1 built by: D15REL
5/24/2017 3:33:59 PM - -------------------------------------------
5/24/2017 3:33:59 PM - Command line parameters:
5/24/2017 3:33:59 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\Vere\Downloads\CRMDeveloperExtensions_v1.3.4.1.vsix
5/24/2017 3:33:59 PM - -------------------------------------------
5/24/2017 3:33:59 PM - Microsoft VSIX Installer
5/24/2017 3:33:59 PM - -------------------------------------------
5/24/2017 3:33:59 PM - Initializing Install...
5/24/2017 3:34:00 PM - Extension Details...
5/24/2017 3:34:00 PM - 	Identifier         : CRMDeveloperExtensions..697f2464-985a-4218-b671-08d51a2e113b
5/24/2017 3:34:00 PM - 	Name               : Dynamics CRM & 365 Developer Extensions
5/24/2017 3:34:00 PM - 	Author             : Jason Lattimer
5/24/2017 3:34:00 PM - 	Version            : 1.3.4.1
5/24/2017 3:34:00 PM - 	Description        : Dynamics CRM & 365 2011/2013/2015/2016 Developer Extensions
5/24/2017 3:34:00 PM - 	Locale             : en-US
5/24/2017 3:34:00 PM - 	MoreInfoURL        : https://github.com/jlattimer/CRMDeveloperExtensions
5/24/2017 3:34:00 PM - 	InstalledByMSI     : False
5/24/2017 3:34:00 PM - 	SupportedFrameworkVersionRange : [4.5.2,)
5/24/2017 3:34:00 PM - 
5/24/2017 3:34:00 PM - 	SignatureState     : Unsigned
5/24/2017 3:34:00 PM - 	Supported Products : 
5/24/2017 3:34:00 PM - 		Microsoft.VisualStudio.Pro
5/24/2017 3:34:00 PM - 			Version : [11.0,14.0]
5/24/2017 3:34:00 PM - 
5/24/2017 3:34:00 PM - 	References         : 
5/24/2017 3:34:00 PM - Signature Details...
5/24/2017 3:34:00 PM - 	Extension is not signed.
5/24/2017 3:34:00 PM - 
5/24/2017 3:34:00 PM - Searching for applicable products...
5/24/2017 3:34:00 PM - Found installed product - Global Location
5/24/2017 3:34:00 PM - Found installed product - Visual Studio Community 2017
5/24/2017 3:34:00 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by jlattimer** [comment]
Yep - this version won't be. Working on a new 2017 as we speak.

**Comment by SigrunO** [comment]
Where can I get the version that supports Visual Studio 2017? The latest release I see is from December. This issue was closed 5 months later.

**Comment by jlattimer** [comment]
Working on the 2017 version here: [https://github.com/jlattimer/CrmDeveloperExtensions2](https://github.com/jlattimer/CrmDeveloperExtensions2)

**Comment by SigrunO** [comment]
Thanks for letting me know where to find it. When do you think a first release to download will be available?
