### ISSUE TITLE
VS 2017

### ISSUE THREAD

**Issue by StephenDKing** [jlattimer/CRMDeveloperExtensions#112]
Would like to use the tool in VS 2017, currently not able to install.

**Comment by Gaander** [comment]
As a temporary fix, you can modify the "extensions.vsixmanifest" inside the .vsix (open with e.g. 7zip) and change the line(s) "<InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[11.0, 14.0]" />" to "<InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[11.0, **15.0**]" />"

**Comment by naveedmcp** [comment]
is it still an open issue? any updates or still need to do a temporary fix @Gaander

**Comment by jlattimer** [comment]
See the new version: [https://github.com/jlattimer/D365DeveloperExtensions](https://github.com/jlattimer/D365DeveloperExtensions) - this version is no longer supported
