### ISSUE TITLE
CRMDeveloperExtensions support for version 9.0

### ISSUE THREAD

**Issue by neoshehpar** [jlattimer/CRMDeveloperExtensions#118]
Hi,
Is CRMDeveloperExtensions compatible with VS 2012 connected with Dynamics 365 v9.0?

**Comment by jlattimer** [comment]
No - this project is no longer being supported in favor of a newer version: https://github.com/jlattimer/D365DeveloperExtensions

Unfortunately though is only going to be for VS 2015+

**Comment by jlattimer** [comment]
Yes

**Comment by neoshehpar** [comment]
I will then try on VS 2017 and let you know. Thanks!
