### ISSUE TITLE
VS 2017 with Dynamics 365 v9.0

### ISSUE THREAD

**Issue by naveedmcp** [jlattimer/CRMDeveloperExtensions#123]
I tried creating plugin project but unable to see Dynamics 365 9.0.X. Please advise if its supported.

![image](https://user-images.githubusercontent.com/31393621/43545045-c8e33d12-95a2-11e8-893d-822d94e1efd0.png)

**Comment by naveedmcp** [comment]
@jlattimer

**Comment by jlattimer** [comment]
See the new version: [https://github.com/jlattimer/D365DeveloperExtensions](https://github.com/jlattimer/D365DeveloperExtensions)
