### ISSUE TITLE
Publishing Image web resource does not work

### ISSUE THREAD

**Issue by damonfutter** [jlattimer/CRMDeveloperExtensions#13]
If you publish a web resource that is an image, the details of the web resource are sent to CRM (display name etc.), but the actual content of the image is not.

From a quick look at the code (although I'm not sure I'm looking at the *right* piece of code), it looks as if it is doing a "File.ReadAllText", which I presume does not work for a binary file.

There is an example of how to load a binary file into a web resource here (half way down the page, titled "Uploading files from disk"):
https://msdn.microsoft.com/en-us/library/gg327924.aspx

**Comment by jlattimer** [comment]
Apparently I never tested this :( Will be fixed in the next release.
