### ISSUE TITLE
WebResource: Connected To CRM Organization Issue

### ISSUE THREAD

**Issue by phuocle** [jlattimer/CRMDeveloperExtensions#15]
Just update CRM to version 7.0.1.129 and now I cannot load the web resource lists.

The output window here

Info: 10/21/2015 5:21:18 PM  Connected To CRM Organization: f259cbd2-6c76-e511-80c8-00155d006603
Info: 10/21/2015 5:21:18 PM  Version: 7.0.1.129
Info: 10/21/2015 5:21:18 PM  Retrieved Solutions From CRM

![image](https://cloud.githubusercontent.com/assets/479729/10632736/caffee38-7818-11e5-928a-c76697cff936.png)

**Comment by jlattimer** [comment]
Do you have another CRM instance you could connect to and test? Another option might be to go into your project folder and delete the CRMDeveloperExtensions.config and re-create your connection. I'm inclined to think right now something in CRM is causing the issue as I can't repro the issue. Does any other detail appear in the Output window? If there was an error being thrown it should appear.

**Comment by jlattimer** [comment]
Closing issue - assuming this was an organization specific issue since I haven't heard anything back.
