### ISSUE TITLE
Linq mocking

### ISSUE THREAD

**Issue by nicolailang** [jlattimer/CRMDeveloperExtensions#2]
Hi Jason, 

I've been testing the framework the past week, and it really looks nice. This gave me the kick to start learning how to unit-test in VS :) I haven't found any errors so far. 

One thing I struggle with is the Linq - I use Linq extensively in my programming, but I can't crack how to mock it? Would you be able to give me some information or point me in a direction where I can read more? Thank you.

**Comment by jlattimer** [comment]
Can you provide an example of what you are looking for?

**Comment by nicolailang** [comment]
Hi Jason, 

Appologies if I am asking to basic questions here, I am just learning how to do unit testing in regards to CRM. I naively thought that mocking would still query / filter my static data, so that my queries are tested too, but I know now that I need to generate specific static data for each scenario tested. 

What I am looking for is a way to return a result in my code when testing for a query where I use linq to access datasets from the XrmServiceContext generated by the SDK early bound tool like: 

```c#
          using (XrmServiceContext svc = new XrmServiceContext(service))
            {
                var q = from c in svc.ContractSet
                        where c.AccountId.Id == accountid && c.StateCode == ContractState.Active
                        select c.ContractServiceLevelCode;
                OptionSetValue[] foundlevels = q.ToArray();
            } 
```
            
To me this is a lot nicer to read than doing it using QueryExpression like: 

```c#
            List<OptionSetValue> list = new List<OptionSetValue>();
            QueryExpression qe = new QueryExpression
            {
                EntityName = "contract",
                ColumnSet = new ColumnSet("contractservicelevelcode"),
                Criteria = new FilterExpression
                {
                    Conditions =
                    {
                        new ConditionExpression
                        {
                            AttributeName = "accountid",
                            Operator = ConditionOperator.Equal,
                            Values = {accountid}
                        },
                        new ConditionExpression
                        {
                            AttributeName = "statecode",
                            Operator = ConditionOperator.Equal,
                            Values = {contract.eStatus.Active}
                        }           
                    },
                    FilterOperator = LogicalOperator.And
                }
            };
            EntityCollection ec = service.RetrieveMultiple(qe);
            if (ec == null)
                return null;
            foreach (Entity cont in ec.Entities)
                if (cont.Contains("contractservicelevelcode"))
                    list.Add((OptionSetValue)cont["contractservicelevelcode"]);
```

To be fair, I did implement my current plugin using QueryExpression and have successfully implemented 7 unit tests using your framework. Great work.

Thank you in advance for any comments.

**Comment by jordimontana82** [comment]
Hi @jlattimer 

Super cool project I just found! :+1: 

@nicolailang  I started another OSS project on Dec 2014 which is an automocking library which generates most of the mocks for us, the developers :P  It's pretty mature now. 

Please check it out, would be great to have some feedback and maybe i could integrate it into this one, as a fork.

https://github.com/jordimontana82/fake-xrm-easy

Thanks!
