### ISSUE TITLE
Webresource not published

### ISSUE THREAD

**Issue by LeszekSzejka** [jlattimer/CRMDeveloperExtensions#28]
Webresources are stored in standard CRM.package project in /Webresources/Script (JScript)/ folder.
In that situation when publishing changes are not being pushed to server. Also "mapping path" can not lead to Webresources/Script (JScript)/ but only to /filename.js (it treats the file like a rootlevel file). Any info about what has happen we can get when trying to compare two files(server and local). It give us exception that curent local file is treated like a root folder.

**Comment by jlattimer** [comment]
Will be fixed in the next release
