### ISSUE TITLE
Unable to map Web Resource marked as IsCustomizable=false

### ISSUE THREAD

**Issue by damonfutter** [jlattimer/CRMDeveloperExtensions#33]
We have a number of unmanaged web resources (script and html) that are marked as IsCustomizable = false.  When we open the Web Resource Deployer, those web resources are not included in the list.  This means that we are not able to map them to a source file in our Visual Studio Solution.  N.B. we are connecting to an _unmanaged_ CRM solution.

In the Web Resource Deployer source code, it looks as if the web resource deployer only includes those that have IsCustomizable=true.  I think that the IsCustomizable flag should only be relevant if you are connected to a managed CRM solution (or if the web resource is managed).

**Comment by jlattimer** [comment]
Removed this check in upcoming 1.3.4.0
