### ISSUE TITLE
Unit Test error

### ISSUE THREAD

**Issue by rodhentz** [jlattimer/CRMDeveloperExtensions#36]
Inside my plug-in creating a organization service using factory.CreateOrganizationService without pass the user id a error of object not reference is throw. I see that pass null is valid in documentation.

My plug-in code

ITracingService tracer = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
PluginExecutionContext context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
IOrganizationServiceFactory factory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
IOrganizationService service = factory.CreateOrganizationService(null);

**Comment by jlattimer** [comment]
This isn't really related to the tool but rather coding a plug-in - why not just pass the user id? 
factory.CreateOrganizationService(context.UserId);
