### ISSUE TITLE
CRM Console Application and 2016

### ISSUE THREAD

**Issue by pab74** [jlattimer/CRMDeveloperExtensions#37]
The Crm Console application references the Xrm.client.dll that doesn't work with CRM 2016.
The CrmConnection maybe should be replaced with CrmServiceClient from tooling namespace  and xrm.client should be removed.
Best regards

**Comment by jlattimer** [comment]
Did you target the latest version of the SDK (8.0.X0 when creating the project? Is this CRM Online or On Premise?

**Comment by pab74** [comment]
Yes, the problem is with CRM 2016 projects. If you create a new crm console application targeting crm 2016 with dll in version 8.xx you can see that the xrm.client.dll is in version 7.xx and it throws an exception as soon as you try to connect to crm.

**Comment by jlattimer** [comment]
The CRM assemblies get installed from NuGet and for the Client and Portal assemblies Microsoft didn't put out an 8.0 version as there weren't changes from the last 7.x version. I'm not able to reproduce an error when connecting to a CRM 2016 Online org. with this scenario. Can you post the exception detail?

https://www.nuget.org/packages/Microsoft.CrmSdk.Extensions/

**Comment by jlattimer** [comment]
Closing this since I haven't heard anything back
