### ISSUE TITLE
Error Retrieving Connections From Config File: Missing CRMDeveloperExtensions.config file

### ISSUE THREAD

**Issue by ixd704** [jlattimer/CRMDeveloperExtensions#44]
I installed CRM Developer Extensions, connected up the CRM 2016 SDK directories as directed in the WIKI and created a Plugin Project.  I then get this error:

Error Retrieving Connections From Config File: Missing CRMDeveloperExtensions.config file
If I look in the project directory, this file does not exists.  Should it auto create?  If not what should the content be?  Do I have to create a different project else first?  I tried a Solution and Web.

I am using Visual Studio 2015 Enterprise and CRM 2016.

**Comment by ixd704** [comment]
Here is the full output...

Error: 11/03/2016 7:37:05 AM  Error Retrieving Connections From Config File: Missing CRMDeveloperExtensions.config file
Info: 11/03/2016 7:38:14 AM  Connected To CRM Organization: b15f2006-b62f-e511-851b-005056901d57
Info: 11/03/2016 7:38:15 AM  Version: 8.0.0.1088
Info: 11/03/2016 7:38:15 AM  Retrieved Assemblies From CRM
Error: 11/03/2016 7:50:11 AM  Error Updating Assembly In CRM: Changes To Assembly Name Require Redeployment
Error: 11/03/2016 7:50:27 AM  Error Updating Assembly In CRM: Changes To Assembly Name Require Redeployment

**Comment by ixd704** [comment]
This is an application that has been migrated from CRM 4 > CRM 2011 > CRM 2013 > CRM 2015 and now CRM 2016 if that makes a difference.  Although I have created new projects for this and then migrated my code over.

**Comment by nzkelvin** [comment]
I got this issue/error too.

**Comment by nzkelvin** [comment]
Looks like the file is in the first project but not the 2nd project I added.

**Comment by jlattimer** [comment]
The config file gets created the first time you create a connection for the selected project in the Connections pane. The error in the log when on the first run is normal as it's trying to read the file which wouldn't have yet been created.

**Comment by jorgecachoh** [comment]
I'm still having this issue:

```
Info: 10/08/2017 10:45:36  Connected To CRM Organization: xxxxxxxxxxxxxxxxxxx
Info: 10/08/2017 10:45:36  Version: 8.2.1.341
Info: 10/08/2017 10:45:36  Retrieved Assemblies From CRM
Error: 10/08/2017 10:45:36  Error Updating Mapping In Config File: Missing CRMDeveloperExtensions.config File
```

CRMDeveloperExtensions.config file exists and VS is able to connect to CRM and retrieve assemblies but not able to save them on the file.

Any fix for this?

Thanks!

**Comment by jlattimer** [comment]
If you are just seeing that message and everything else works then you are fine. That message will get displayed the first time to connect up to a project as the config file hasn't been created yet.

**Comment by jorgecachoh** [comment]
The issue is the Assembly combo in Visual Studio is not being fullfiled because Visual Studio says CRMDeveloperExtensions.config doesn't exist (it exists and it contains CRM connection details) so I can't upload updated plugins to CRM.
