### ISSUE TITLE
Version 1.3.1.0: Missing assembly OutputLogger

### ISSUE THREAD

**Issue by nakaod** [jlattimer/CRMDeveloperExtensions#48]
I just installed version 1.3.1.0 and when opening a CRM solution (VS 2015 Enterprise, 14.0.24720.00 Update 1) the following error is logged to the VS activity log:
"Could not load file or assembly 'OutputLogger, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6b6fea021edb4af6' or one of its dependencies." (see attached extract from ActivityLog.xml)

Also, when opening the context menu on a project and choosing e.g. "CRM Developer Extensions" --> "Plug-in Developer", an exception window appears: "Exception has been thrown by the target of an invocation."
[ActivityLog.xml.txt](https://github.com/jlattimer/CRMDeveloperExtensions/files/204491/ActivityLog.xml.txt)

**Comment by tvenhaus** [comment]
I am having the exact same issue.  Is there a way to downgrade to the previous version?

**Comment by veljko** [comment]
Building OutputLogger.dll from source and adding it to AppData\Local\Microsoft\VisualStudio\[version]\Local\Extensions\[generated name here] will probably fix the issue until fixed version comes out...

**Comment by jlattimer** [comment]
I put out a new release (1.3.2.0), can someone verify this fixes the issue? Thanks!

**Comment by nakaod** [comment]
Works like a charm now. Thanks!
