### ISSUE TITLE
Error after extracting CRM 2016 online solution and build in VS 2015 

### ISSUE THREAD

**Issue by SudhansuNayak** [jlattimer/CRMDeveloperExtensions#49]
After extracting the required solution using CRM Deplover extension Solution packager, we are facing following issue.

First - the complete  extraction /unpack  is successful in 3rd attempts , if the solution is big.
Second issue: while build the project having unpack solution components files , we are getting following error. 
Error		Unable to resolve the type 'http://schemas.microsoft.com/netfx/2009/xaml/activities:Activity' or one of its arguments

Alos unable to open .xaml file in VS

Can you please suggest

**Comment by jlattimer** [comment]
In the next release the time allotted to unpacking is increased to accommodate larger solutions, hopefully that will fix that issue. 

I'm not sure what project you're trying to build, but it doesn't sound like it's related to the wrapper around the solution packager tool.
