### ISSUE TITLE
Plug-in Deployer - Assembly selection empty after connection to organisation

### ISSUE THREAD

**Issue by liorabel** [jlattimer/CRMDeveloperExtensions#51]
As the title says.
I have gone through the following steps numerous times with the same result. There are no assemblies listed so I can't deploy to CRM.
1. Delete all existing CRM connections from the Plug-in Deployer window.
2. Create a new connection for my dev environment with full admin rights.
3. Connect successfully.
4. The list of assemblies is empty.

The Plug-in Registration Tool button works as expected and I am able to register the plug-in for initial use. The problem is that for later updates I still need to do it manually as the Deployer does not seem to be working.

I am using version 1.3.2.0 on Visual Studio 2013 Community Edition.

**Comment by Wobin** [comment]
I have the same issue 

Using 1.3.2.0 in VS2015 Enterprise connecting to a MSCRM 2011 On-Premesis 
![failtoretrievedll](https://cloud.githubusercontent.com/assets/2107/15921930/59e7906e-2e68-11e6-8bca-bf73fb65860e.png)

**Comment by rgallini** [comment]
Same here. VS2013 Professional Update 4 , extension version 1.3.2.0

**Comment by jlattimer** [comment]
In the project folder, can you open CRMDeveloperExtensions.config after closing the project/VS and see if anything is listed in the <Assemblies> element? You should be seeing a <Assembly> element with OrgId, ProjectName, and AssemblyId listed. 

Can you also verify in the Connections pane that a project is in fact selected?

**Comment by tw0sh3ds** [comment]
I believe I know the reason - the tool is trying to map the project only to the projects that are under the Solution (in function GetProjectByName), so if you have a project under a folder it would not get mapped. It was done correctly in ConnectionPane (all the projects are found, also subprojects).

**Comment by eehret** [comment]
This bug seems to be affecting me too... which is a shame because I was eager to find a tool that handles multiple assembly versions, since the original Microsoft CRM Developer Toolkit does not seem to.

Plugin registration tool handles my scenario but is a pain to use, especially when I want to always alter the plugin or workflow step properties of upon registration (e.g. change the "friendly name" to something actually friendly)

Any chance this bug will be fixed soon?  Anything I can do to help?  :)

**Comment by gobusnuts** [comment]
tw0sh3ds is on the right track.

I moved my project out of the folder to fall under the root solution in the solution manager. After reconnecting the CRM Connection, I had the list of solutions.

**Comment by liorabel** [comment]
Could this be enabled for project under folders as well?
Simple and flat solutions aren't always possible.

**Comment by jlattimer** [comment]
Should be fixed - going to try and have another release out this coming week.
