### ISSUE TITLE
It's not possible to unpackage both (managed and unmanaged) solutions

### ISSUE THREAD

**Issue by psharkin** [jlattimer/CRMDeveloperExtensions#52]
CRMDeveloperExtensions has an ability to upload Managed packed by enabling "Download Manged Solution?" flag in Solution Packager view. But in fact it doesn't extract managed solution and then there is not chance to pack managed solution based on the source code.

Whereas SolutionPackager.exe tool has an ability to extract both managed and unmanaged solutions into the same folder and then use this code to pack both managed/unmanaged solutions.

Is it possible to add managed solution extraction to Solution Packager?

**Comment by ikurtev** [comment]
Greetings,

This functionality is included in a pull request I submitted here: https://github.com/jlattimer/CRMDeveloperExtensions/pull/39. 

Ivan

**Comment by psharkin** [comment]
Great news.

Meantime could you give your version of extension? So I can use it while you pull request is under review.

Thanks is advance.

**Comment by jlattimer** [comment]
Should be possible in the next release
