### ISSUE TITLE
Solution Packager: CRMDeveloperExtensions.config deleted after Unpackage Solution

### ISSUE THREAD

**Issue by punyargybargy** [jlattimer/CRMDeveloperExtensions#53]
The config file is removed after unpacking the solution. That means I need to reconfigure the Solution Packager every time I want to run it.

Please note: I am using git for source control.

**Comment by jlattimer** [comment]
I can't repro this, is there any other detail you can add?

**Comment by punyargybargy** [comment]
It seems that prior to unpacking the solution, the solution (packaging solution) folder is completely wiped. That also removes the config file. Only the unpacked items will be added to the solution. After that process, the config file is still missing. Does that help you?

**Comment by jlattimer** [comment]
I'll bet you have the config file included in the solution! That would explain why it's getting deleted. Anyway, added a fix to prevent this from being deleted.
