### ISSUE TITLE
System.MissingMethodException error

### ISSUE THREAD

**Issue by diver7** [jlattimer/CRMDeveloperExtensions#54]
I created a new solution and added a CRM Plug-in Project. I then added the CRM SDK AccountNumberPlugin.cs file as an example to test with. Then I added a CRM Pug-in Unit Test Project to the solution. In the Unit Test project I added a new CRM Plug-in Unit Test. I'm just trying to create a simple example to see how this works. I can build the Solution without errors but when I try to run the TestMethod1 I get the following error:

Message: System.MissingMethodException: Constructor on type 'Microsoft.Crm.Sdk.Samples.AccountNumberPlugin' not found.

The error appears to be thrown by the Activator.CreateInstance line in the InvokePlugin function. Is there something I'm missing?

**Comment by jlattimer** [comment]
When you generate a plug-in class from the template, it adds a constructor which accepts the secure & unsecure configurations, which are passed in Activator.CreateInstance. The code you copied from the SDK doesn't have the class constructor accepting those parameters - if you added this it should work as expected. 

#region Secure/Unsecure Configuration Setup
private string _secureConfig = null;
private string _unsecureConfig = null;

public AccountNumberPlugin(string unsecureConfig, string secureConfig)
{
	_secureConfig = secureConfig;
	_unsecureConfig = unsecureConfig;
}
#endregion
