### ISSUE TITLE
Custom entity -> Create plugin. "An error while trying to load components from the Plug-in Registration Tool"

### ISSUE THREAD

**Issue by eliotstock** [jlattimer/CRMDeveloperExtensions#55]
This is on Visual Studio 2015 Community Edition. Dynamics CRM Developer Extensions 1.3.2.0.

Steps to repro:

1. Tools -> Options -> CRM Developer Toolkit. The path to the tool is valid (in my case, C:\dev\dynamics_crm_2016_sdk\Tools\PluginRegistration)

2. Connect to CRM Online and go to the CRM Explorer.

3. Right click on a custom entity, Create Plug-in.

4. Get error dialog "An error while trying to load components from the Plug-in Registration Tool"

There's no output in the output pane for CRM Developer Extensions.

**Comment by jlattimer** [comment]
The CRM Developer Toolkit is Microsoft's developer tools, not mine. You should raise an issue here: https://crmideas.dynamics.com/ideas/
