### ISSUE TITLE
Can only check one entity at a time after "Start from CRM", "Add existing items"

### ISSUE THREAD

**Issue by eliotstock** [jlattimer/CRMDeveloperExtensions#58]
Using SDK 8.0.0.0, extention 1.3.2000.7300, VS 2015 Community.

Steps to repro:

1. File -> New Project -> New Visual Studio Solution Template for Dynamics CRM, check "Create directory for new soltuon"
2. Reconnect to CRM
3. Start from CRM
4. Select existing Dynamics CRM Solution
5. Add existing items
6. Asset type: entity
7. Check an entity. Checkbox works.
8. Check another. The previous one becomes unchecked.

**Comment by jlattimer** [comment]
This looks like it relates to the Microsoft created developer tooling and not this project. You should raise an issue on https://connect.microsoft.com/
