### ISSUE TITLE
Project Templates?

### ISSUE THREAD

**Issue by colinbashbash** [jlattimer/CRMDeveloperExtensions#63]
I was having an issue installing the regular dynamics CRM developer tools, so I tried just installing this extension. These are the project guids of the c# projects from our vendor that won't open for me. Should any of these open just using this extension?
Plugin: 4C25E9B5-9FA6-436c-8E19-B395D2A65FAF
CRM Package(?): 88A30576-7583-4F75-8136-5EFD2C14ADFF
Workflow: 089D5B2A-9C2F-4B6D-9F7B-CFD25BB0B7F4

**Comment by jlattimer** [comment]
I believe those are the projects generated by the previous Microsoft tooling - this extension is not compatible.
