### ISSUE TITLE
Web Resource Deployer doesnt show all Solutions

### ISSUE THREAD

**Issue by MaorWithM** [jlattimer/CRMDeveloperExtensions#66]
The Web Reasource Deployer is missing 2 solutions, it is not supposed to show all the solutions?

**Comment by jlattimer** [comment]
Can you describe the structure in the solution? Is there solution folders, sub-solution folders, etc.?

**Comment by phuocle** [comment]
If I remember in the solution without web-resource the web resource pane didn't add to the combo-box solution. In this case, you cannot see the solution.

But in the add new web resource dialog, you can see it.

Sometime, this make user confuse.

**Comment by jlattimer** [comment]
OK I think I've got this one fixed and will be in the next release.
