### ISSUE TITLE
Unable to connect to CRM Online 

### ISSUE THREAD

**Issue by peterbjorkmarker** [jlattimer/CRMDeveloperExtensions#72]
I am getting the following error in Fiddler when connecting using the Plugin Deployer:
ACS10002: An error occurred while processing the SOAP body. ACS50000: There was an error issuing a token. ACS50001: Relying party with identifier '[My CRM Online instance]' was not found.
Trace ID: 961229ff-6a4c-416a-b755-692fb796dabc

To the best of my knowledge it looks to be the same issue as described here:
https://community.adxstudio.com/forums/adxstudio-portals/e7c41187-c66a-e611-9400-000d3a1044cb

At the bottom there is a solution saying that you need to ref the latest SDK dlls. Tried just dumping new dlls in my extensions folder but to no avail (VS crashed). Tried to do a pull req but I only have VS2015 installed and thought you may not want to upgrade that right now.

**Comment by ShawLevin** [comment]
I am also getting this issue. My team saw this problem in the LinqPad for CRM driver, our custom code and the CRM Migration Utility.

We addressed it in our code by switching from using the Org Service to the Org Proxy class for our connections.

I see this line in the WebResourceDeployerPackage.cs (174):

using (OrganizationService orgService = new OrganizationService(connection))

I think these have to be updated to something like this. The getServiceUri 

using (var _orgService = new OrganizationServiceProxy(new Uri(getServiceUriFromUrl(serverUrl)), null, connection.ClientCredentials, null))

Also, this came from the MSFT SDK samples (I think):

        private string getServiceUriFromUrl(string url)
        {
            var uri = new Uri(url);
            var host = uri.Host;

            var environment = host.Split('.');

            return "https://" + environment[0] +
                                   ".api.crm.dynamics.com/XRMServices/2011/Organization.svc";


        }

**Comment by jlattimer** [comment]
Hoping this will get addressed with the next release which will be using newer SDK dlls for the connection

**Comment by jlattimer** [comment]
New version released - please re-check

**Comment by ShawLevin** [comment]
Looks to be working for me now. Thanks!
