### ISSUE TITLE
Plugin Registration tool cannot connect

### ISSUE THREAD

**Issue by aslwinlam** [jlattimer/CRMDeveloperExtensions#74]
I have an environment with PING Fed as Claims for CRM.  WS-trust was setup with Plugin Registration tool and is working fine outside of the VS 2015.  With the plugin registration of the CRMDeveloperExtensions.  FYI, the PING does not support tls1.0.   I got the following error :

Error: 11/1/2016 10:54:06 AM  Error Connecting To CRM: The authentication endpoint Kerberos was not found on the configured Secure Token Service!

**Comment by jlattimer** [comment]
Not sure that I can even hope to support this as I don't have an environment to test against. Possible it might be fixed in the next release with the coming connection changes
