### ISSUE TITLE
Could not find a part of the path when creating "crm solution Package"

### ISSUE THREAD

**Issue by enhanna** [jlattimer/CRMDeveloperExtensions#78]
Hello,

I'm very new to this and this looks excellent.  All project load except for the crm solution package"  I get could not find a part of the path.  How do you fix that?

**Comment by jlattimer** [comment]
Under Tools -> Options -> CRM Developer Extensions -> Solutions Packager did you fill in the path the the SDK bin folder?

**Comment by enhanna** [comment]
Hi Yes I do.

I’m using visual studio 2015 and sdk 2016.

[Failure] Could not find a part of the path 'c:\users\emad\documents\visual studio 2015\Projects\CRMSolutionPackage2\CRMSolutionPackage2\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs'.
[Failure] Could not find a part of the path 'c:\users\emad\documents\visual studio 2015\Projects\CRMSolutionPackage2\CRMSolutionPackage2\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs'.
[Failure] Could not find a part of the path 'c:\users\emad\documents\visual studio 2015\Projects\CRMSolutionPackage2\CRMSolutionPackage2\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs'.


Thank you




Emad Hanna

**Comment by jlattimer** [comment]
Not sure on this one. If you run the solution packager tool from the SDK manually does it work?

**Comment by jlattimer** [comment]
Close for lack of response
