### ISSUE TITLE
Managed Security Roles Not Extracted from Unmanaged Solution Package

### ISSUE THREAD

**Issue by cbritton123** [jlattimer/CRMDeveloperExtensions#81]
Hi John,

When we include modified versions of the out-of-the-box (managed) security roles in our unmanaged solution packages (ZIP), the CRM Developer Extensions do not extract these as separate XML files for each security role under the corresponding Roles folder. However, these do appear in the customizations.xml file in the solution package's ZIP file.

Is this normal behavior for the CRM Developer Extensions? If not, would it be possible to fix them so that we can track our modifications to the out-of-the-box security roles?

Thanks and keep up the good work!

**Comment by jlattimer** [comment]
Since I'm using the SDK Solution Packager we're at its mercy as to what it does. Pretty sure since it's probably designed to not handled the managed items.
