### ISSUE TITLE
How to specify message or stage in context of Unit Test

### ISSUE THREAD

**Issue by bwmodular** [jlattimer/CRMDeveloperExtensions#87]
Sorry if I'm missing something obvious, but I cannot work out how to specify in my Plugin Unit tests the message (Create,Update,Delete) or the stage (pre-validation, pre/post-operation) in the context of the plugin being tested. I'm sure it must be possible, but I can't work it out.

Thanks,
Ben

**Comment by bwmodular** [comment]
I've worked out how to do it by setting up the mocked context in the Invoke plugin method:
pluginContextMock.Setup(t => t.Stage).Returns(10);
pluginContextMock.Setup(t => t.MessageName).Returns("Create");

Would you consider making these private package level variables which could be set in the TestInitialise method? Or I could do this if you think this would be an ok thing to do? I'd consider creating a couple of enums for the different stages and messages.

**Comment by jlattimer** [comment]
The approach was somewhat of a template - sure we could configure the context and pass it in but I thought that might the tests more complex. What you did is normally the approach I take
