### ISSUE TITLE
Error: 2/16/2017 11:59:26 AM  Error Updating Assembly In CRM: Object reference not set to an instance of an object.    at PluginDeployer.PluginList.UpdateCrmAssembly(AssemblyItem assemblyItem, CrmServiceClient client)

### ISSUE THREAD

**Issue by mkcgphy** [jlattimer/CRMDeveloperExtensions#94]
While I am trying to deploy custom workflow developed using SDK Toolkit I am getting following error 
 

Info: 2/16/2017 11:59:20 AM  Connected To CRM Organization: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
Info: 2/16/2017 11:59:20 AM  Version: 8.2.0.780
Info: 2/16/2017 11:59:21 AM  Retrieved Assemblies From CRM
Error: 2/16/2017 11:59:26 AM  Error Updating Assembly In CRM: Object reference not set to an instance of an object.
   at PluginDeployer.PluginList.UpdateCrmAssembly(AssemblyItem assemblyItem, CrmServiceClient client)

Any suggestion ?

**Comment by jlattimer** [comment]
Can you please turn on the Xrm.Tooling logging option under the Visual Studio options and then post the log? I suspect it's going to show the same issue others are having, which at the moment I have no solution for. I hate to point fingers, but I don't think this is an issue with the extension.

**Comment by mkcgphy** [comment]
I uninstalled visual studio and installed again and it is resolved.

Thanks
