### ISSUE TITLE
Error connecting CRM

### ISSUE THREAD

**Issue by xjomanx** [jlattimer/CRMDeveloperExtensions#96]
May be I doing something wrong.
I choose on-perm. using Win. integrated security. It generates string: http://servername/orgname
then I replace it on https://servername/orgname
and place a "Connect" button.
Then I receive an error:
"Object reference does not point to an instance of an object".

P.S.
http://servername/orgname
works fine

**Comment by mppowe** [comment]
Are you able to connect to the https address in a browser ok?  Is it using a real signed cert, or a self-signed cert?

**Comment by xjomanx** [comment]
Yes. The same address (https://server/org) in browser connect to CRM.
This is cert from a domain certification center.

**Comment by xjomanx** [comment]
I found solution of a problem.
The problem is that "/XRMServices/2011/OrganizationData.svc" not worked with https protocol.
I changed the setting of CRM. Now "/XRMServices/2011/OrganizationData.svc" working throw https and plug-in works fine.
