### ISSUE TITLE
Visual Studio 2017?

### ISSUE THREAD

**Issue by ChrisH-ISC** [jlattimer/CRMDeveloperExtensions#98]
Just curious to see if you are planning to have this listed on the VS 2017 marketplace?

**Comment by jlattimer** [comment]
Hopefully be able to start working on it soon

**Comment by jamesnovak** [comment]
I just rebuilt my machine and installed VS 2017 and these tools are a crazy time saver, so I applied the updates for VS 2017 to a local copy for myself.  This included changes to each project but they involved updating references only, no business logic changes. It did not take me too long and seems to work fine so far, some quick testing on the Web Resource deployment tool and new project templates.
Of course, this update breaks backwards compatibility for VS 2015, but it will allow me to continue using the tool between updates.

**Comment by jlattimer** [comment]
I'm in the process of revamping everything and probably releasing a new version which only targets 2015+ which is built on VS 2017. Gives me a chance to clean up some of the older artifacts needed for the older versions of VS, remove the dependency on SideWaffle for templating in favor of the OOB templating, adding language localization, replacing the custom login with the Xrm.Tooling control, and a bunch of other stuff that should make it better.

**Comment by thowur** [comment]
I like your ideas and appreciate your honorable work for the whole dynamics crm community very much. Very good job all the Times! 
What is your expection you will finish your CRMDeveloperExtensions for VS2017?

**Comment by zaha** [comment]
Waiting for this as well.
Thanks for your work on this extension! 👍

**Comment by jlattimer** [comment]
Working on it now
